### ISSUE TITLE
Could not find a valid gem 'saxon-xslt' in any repository

### ISSUE THREAD

**Issue by yegor256** [fidothe/saxon-xslt#15]
Am I doing something wrong:

```
$ gem install saxon-xslt
ERROR:  Could not find a valid gem 'saxon-xslt' (>= 0) in any repository
ERROR:  Possible alternatives: saxondale
```

**Comment by fidothe** [comment]
`saxon-xslt` is JRuby only - you'll get that error if you use MRI's `gem` and not JRuby's.

**Comment by yegor256** [comment]
@fidothe any chance to port this library to Ruby?

**Comment by fidothe** [comment]
It is a Ruby library already. To run with MRI would need a port of Saxon from Java to C, with a license that would allow building and using in an open source project, and that doesn't exist. (There is a C version, but it's compiled from Java using a proprietary toolchain which means it can't be distributed

So, unfortunately it's physically impossible at the moment.

The best you could manage would be a wrapper that shells out to Java in the background - and that's something you can easily do yourself, with no need for a gem.
