### ISSUE TITLE
 An error occurred while installing saxon-xslt (0.7.2), and Bundler cannot continue

### ISSUE THREAD

**Issue by lmcglohon** [fidothe/saxon-xslt#17]
I am working on an open source project (https://github.com/archivesspace/archivesspace) that is used by folks on both linux and windows machines and have been trying to build releases on a windows machine. Apparently, even though I have installed the saxon-xslt gem on the machine, with I run my bundler, it can’t be found. We have recently upgraded to JRuby 9.x and I was wondering, since you are not testing JRuby 9 with travis, that there might be some sort of an issue there.

I am using ant and bundler to install all the required gems but am getting these error messages:
     [java] Installing saxon-xslt 0.7.2
     [java]
     [java] Errno::ESRCH: No such process - No message available

     [java] An error occurred while installing saxon-xslt (0.7.2), and Bundler cannot
     [java] continue.
     [java] Make sure that `gem install saxon-xslt -v '0.7.2'` succeeds before bundling.

However, I know I have saxon-xslt installed:

$ gem list
did_you_mean (default: 1.0.1)
jar-dependencies (default: 0.3.10)
jruby-openssl (default: 0.9.20 java)
jruby-readline (default: 1.1.1 java)
jruby-win32ole (0.8.5)
json (default: 1.8.3 java)
minitest (default: 5.4.1)
net-telnet (default: 0.1.1)
power_assert (default: 0.2.3)
psych (default: 2.2.4 java)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
**saxon-xslt (0.7.2 java)**
test-unit (default: 3.1.1)

Any help would be greatly appreciated!

**Comment by fidothe** [comment]
I'm trying to understand how your project actually deals with gems. I can see references to Bundler and a `Gemfile` in the startup scripts, and in the Ant `build.xml` but it's not clear from your output which part of the build task is failing. There are several Gemfiles in different bits of your project, but only the one in `/backend` has any reference to `saxon-xslt`. If I look at output from your Travis builds I can see it being installed there

(https://travis-ci.org/archivesspace/archivesspace/jobs/304037916#L1965)

I'm a complete ignoramus about Ant, unfortunately, but from reading the invocation instructions inside your startup scripts I can see several references to overriding `$GEM_HOME`, which makes me think that your locally-installed gems might be ignored in favour of whatever gets installed by your build process.

I'll set up a Windows VM and see if I get the same results I'll start by trying the instructions at http://archivesspace.github.io/archivesspace/user/archivesspace-build-system/

**Comment by lmcglohon** [comment]
@fidothe I am new to Ant as well, but I see what you mean about the gem-home being overwritten. I have been wanted to dig into our build process for a while. This seems like an excellent opportunity to do just that. I don't have this problem when building on a mac - so hopefully that is a clue to point me in the correct direction.

**Comment by cdesai-qi** [comment]
I had a similar issue with my install. This issue maybe a little old, but comes up first on the search result. So I am posting my solution here.

**Error:**
```
[java] An error occurred while installing saxon-xslt (0.8.0), and Bundler cannot
[java] continue.
```
**Cause:**

Mine turned out be an issue with the character limit for fully qualified path of a file in Windows. Windows restricts it to 260 characters.

In saxon-xslt gem, there is an YML file that is 7 or 8 directories deep. So the fully qualified path for that particular file ended up being over the limit.

The offending file:
`C:\Users\XXXXXX\development\aspace\archivesspace\build\gems\gems\saxon-xslt-0.8.0-java\spec\fixtures\cassettes\Saxon_SourceHelper\returning_a_StreamSource\StreamSource_systemId\for_inputs_where_we_can_infer_the_path_or_URI\is_set_to_an_open-uri_d_URI_s_URI.yml
`

**Solution:**

So I moved my archivesspace directory to root of C: driv., and the bundler process succeeded.

**Comment by fidothe** [comment]
Ah, that's fascinating. Not least because those fixtures are supposed to be excluded from the gem package. I'll fix that and let's see if that fixes these install problems

**Comment by fidothe** [comment]
@lmcglohon @cdesai-qi i've cut new releases `0.7.2.1` and `0.8.2.1` that don't have those super-long paths in the `.gem` anymore. Can you try building on windows again and see if that's fixed?

**Comment by fidothe** [comment]
My test install of ArchivesSpace on Windows now completes successfully, whereas before it didn't. I'm going to call this one fixed.

**Comment by fidothe** [comment]
Thanks again @cdesai-qi - i'd have been chasing my tail on this for months without your help!

**Comment by cdesai-qi** [comment]
Hey @fidothe! Sorry for the late response.  I did test 0.8.2.1 a few days ago. I did not see any issues related to filepath in Windows.  Thank you for putting out a new release.
