### ISSUE TITLE
Request bump to Saxon 9.8.0.7 or higher 9.8 version to avoid breakage of XSLT 1.0 backcompat

### ISSUE THREAD

**Issue by pobocks** [fidothe/saxon-xslt#30]
Saxon's 9.8 series made a breaking change, dropping support for XSLT 1.0 compat mode.  This will happen again if/when bumped to 9.9, but in the meantime, a bump to later 9.8 series maint releases should fix this.

Relevant SE:
https://stackoverflow.com/questions/45595852/xtde0160-xslt-1-0-compatibility-mode-is-not-available-in-this-configuration-in

**Comment by fidothe** [comment]
I need to check, but I'm 99% certain that 9.8.0.15 is bundled already

**Comment by pobocks** [comment]
Hmm, I'll check if I've got something pinning it. I looked at the last commit affecting saxon, and it just says "9.8," and the test fixture has a version bump in the way I'd have bumped it if Saxon was telling me it didn't want to do 1.0 anymore.

**Comment by fidothe** [comment]
It was indeed 9.8.0.6 - have bundled 9.8.0.15 and cut a new release (0.8.2.2)

**Comment by pobocks** [comment]
Thanks!
