### ISSUE TITLE
Pass parameters to XML Processor (Schematron)

### ISSUE THREAD

**Issue by pobocks** [fidothe/saxon-xslt#6]
As far as I can tell, there's no way to pass a param to an XSLT that's being compiled or run, except by including it in the XSLT file before running.  The Saxon command-line parser is able to accept variables, so it should be possible, but I'm relatively new to Saxon, and haven't figured out what would need to happen to extend saxon-xslt to do it.

The case I'm trying to solve is using this library to run Schematron validators over EAD files.  

Right now, as a workaround, my only option is to parse, alter, and write the XSL file to a temporary file, which must be in the same directory as the rest of schematron (because it works via includes).  

The application in question is available here: https://github.com/harvard-library/schematronium

**Comment by pobocks** [comment]
Having looked at it slightly more, it looks like adding a setParameter call to the Saxon::XSLT#transform function would fix the problem... 

I'm going to try and get a working PR, please let me know if this seems like a bad path or there's a better way.

**Comment by fidothe** [comment]
Thanks for picking this up!

Looking at Nokogiri's transform implementation, you can pass params as an array to `#transform` or `#apply_to`*. Judging by other libxslt-using wrappers, it's basically an array of param name followed by param value. It'd be great if you could follow that form so that we can maintain API compatibility with Nokogiri.

I look forward to seeing the PR.

*Looks like I really should add an `#apply_to` method to do transform-then-serialize a la Nokogiri too :-)

**Comment by pobocks** [comment]
Hmmm... I have a working version with params passed into transform as a hash (name -> k, value -> value).  I'll look at the Noko version.

Do you have preferences for how to set up the test? I basically wrapped the existing text XSL in an xsl:choose on the param, and provided a default which emits what's expected already, and a special value if the param is set differently. Since everything's conditionally in the existing XSL, this seemed least-difference, but I'm def open to extracting it into a separate test XSL.

Also, as this is a new feature, version to 0.6.0?

**Comment by pobocks** [comment]
Hmm... Actually, since Saxon API means having to split out key and value (especially if eventually supporting other constructor signatures for QName), I think there's a strong case for params as hash. Noko seems to take k=v as a single string.

Anyway, take a look and lemme know what you think!

**Comment by pobocks** [comment]
So, as far as I can tell, supporting other contructor signatures for QName seems pointless, but I still think hash makes more sense than array of strings there. Alternately, it could take either, I suppose. 

I don't know, seems like a matter of taste, and it's your library, so whatever thou decidest, I shalt be happy to implement ;-)

**Comment by fidothe** [comment]
Let's move this conversation to the PR now...

**Comment by fidothe** [comment]
Merged, many thanks :-)
