### ISSUE TITLE
Users should be able to replace default processor

### ISSUE THREAD

**Issue by pobocks** [fidothe/saxon-xslt#8]
So, currently, you can either get a default (nil) processor, and be able to use convenience functions on the Saxon module, or you can use a custom processor, and have to use that in all cases.  

This is especially a problem if you have a gem using the default processor, and need to set config that matters to its consumers but not to the gem generally.

In my case, I need to turn line-numbering on, so I can post-process the XML to associate line numbers with schematron failed-asserts.  I either have to build this into the schematron checker library, which won't necessarily be used by people who care about line numbers, or else parse the XML file with two separate processors.

PR incoming.  Again, if I'm missing why this is a bad idea, let me know - I'm very new to Saxon.

**Comment by fidothe** [comment]
How do you turn line numbering on? Is it a creation-time only thing for the processor or could you call methods on the processor from `Saxon::Processor.default`?

**Comment by pobocks** [comment]
Creation-time, as far as I can tell. You pass in a configuration when you
create a processor.  I'll do more looking, but since setting it would
invalidate the processor for anything run through it be for it was set, I'd
be surprised if there was a runtime option.

**Comment by pobocks** [comment]
Theoretically according to docs it should be possible, but in practice, I haven't gotten it to work.

I think, either way, I think it would be nice to be able to create a processor with exactly the config you want (as opposed to "default plus these five individual modifications") and use the convenience methods with it.

**Comment by pobocks** [comment]
Ok, I've officially gotten it to work; the key turns out to be constructing property strings correctly.

```Ruby
Saxon::Processor.default.to_java.setConfigurationProperty("http://saxon.sf.net/feature/linenumbering", true)
me = Saxon::XML(File.open('spec/fixtures/eg.xml'))
me.xpath("input").line_number
```

I think most convenient way for users is to provide helper methods for getting and setting individual properties, as well as a method for whole-cloth replacing the processor (or replacing the configuration).  Propose that helper method should take a string or a symbol and convert to the URI-ish thing actually expected.

**Comment by fidothe** [comment]
You can already just create a processor implementation and call the `XML()` and `XSLT()` methods on it exactly as you would with e.g. `Saxon::XSLT()`. I'm still unsure as to how wise it is to encourage modificiation or replacement of the default processor when it's so easy to create your own and use that everywhere you need to... Convenience methods for the configuration stuff sound great though. I need to refresh my memory about how the configuration stuff works, and then let's talk about what would work for you...

**Comment by pobocks** [comment]
Hmmm.

Thinking about this more closely, I think just the helper methods would be
essentially fine.  Empty config for Saxon means "default values" anyway, as
far as I know, so it's not going to be substantially different to input XML
to that effect vs running processor.set_config(:setting => val) or
something, particularly if we handle multiple values.

I'll get this worked up sometime today. I'm thinking
`Processor#get_config(config:sym), Processor#set_config(config:sym =>
value, ...)`

BTW, thanks for being so responsive on this!

**Comment by pobocks** [comment]
@fidothe pinging in case this has fallen off your radar

**Comment by fidothe** [comment]
@pobocks How does #10 grab you?

**Comment by fidothe** [comment]
Closing after #10 seems to do the trick
